

DROP DATABASE IF EXISTS `dqmc`;
CREATE DATABASE `dqmc`;

USE `dqmc`;

GRANT ALL ON dqmc.* TO dqmc@localhost IDENTIFIED BY 'dqmc123';

DROP TABLE IF EXISTS `city`;
CREATE TABLE `city` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NOT NULL,
  `latitude` DECIMAL(10) DEFAULT NULL,
  `longitude` DECIMAL(10) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_UNIQUE` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `chinchorro`;
CREATE TABLE `chinchorro` (
  `id` INT(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `urb` VARCHAR(45) DEFAULT NULL,
  `number` INT(10) DEFAULT NULL,
  `apt` INT(6) DEFAULT NULL,
  `street` VARCHAR(45) DEFAULT NULL,
  `zip` INT(5) DEFAULT NULL,
  `plus4` INT(4) DEFAULT NULL,
  `latitude` DECIMAL(20,0) NOT NULL,
  `longitude` DECIMAL(20,0) NOT NULL,
  `kmarker` INT(11) DEFAULT NULL,
  `city_id` INT NOT NULL,
  FOREIGN KEY (`city_id`) REFERENCES city(`id`) 
  ON UPDATE CASCADE ON DELETE RESTRICT,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_UNIQUE` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
